nav: # Navigation for Russian (will need translation)
    - Главная: index.md
    - Практические занятия:
        - Подключение к WIS2 через MQTT: practical-sessions/connecting-to-wis2-over-mqtt.md
        - Доступ к виртуальной машине студента: practical-sessions/accessing-your-student-vm.md
        - Инициализация wis2box: practical-sessions/initializing-wis2box.md
        - Настройка наборов данных в wis2box: practical-sessions/configuring-wis2box-datasets.md
        - Настройка метаданных станции: practical-sessions/configuring-station-metadata.md
        - Мониторинг уведомлений WIS2: practical-sessions/monitoring-wis2-notifications.md
        - Преобразование данных SYNOP в BUFR из командной строки: practical-sessions/converting-synop-data-to-bufr.md
        - Преобразование данных SYNOP в BUFR с использованием wis2box-webapp: practical-sessions/converting-synop-data-to-bufr-form.md
        - Преобразование данных CSV в BUFR: practical-sessions/converting-csv-data-to-bufr.md
        - Автоматизация приема данных: practical-sessions/automating-data-ingestion.md
        - Добавление заголовков GTS к уведомлениям WIS2: practical-sessions/adding-gts-headers-to-wis2-notifications.md
        - Настройка рекомендуемого набора данных с контролем доступа: practical-sessions/datasets-with-access-control.md
        - Загрузка данных из WIS2: practical-sessions/downloading-data-from-wis2.md
        - Обнаружение наборов данных из Глобального каталога обнаружения WIS2: practical-sessions/discovering-datasets-from-wis2-gdc.md
        - Запрос данных с использованием API wis2box: practical-sessions/querying-data-using-the-wis2box-api.md
        #- Работа с данными BUFR: practical-sessions/bufr-command-line-tools.md
    - Шпаргалки:
        - Linux: cheatsheets/linux.md
        - Docker: cheatsheets/docker.md
        - WIS2 в коробке: cheatsheets/wis2box.md
    - Шаблоны csv2bufr:
        - AWS hourly: csv2bufr-templates/aws-template.md
        - DAYCLI: csv2bufr-templates/daycli-template.md